export const SimplyOutlookMcpEnvs = {
  SIMPLY_OUTLOOK_MCP_CLIENT_ID: "SIMPLY_OUTLOOK_MCP_CLIENT_ID",
  SIMPLY_OUTLOOK_MCP_TENANT_ID: "SIMPLY_OUTLOOK_MCP_TENANT_ID",
  SIMPLY_OUTLOOK_MCP_DISABLED_TOOLS: "SIMPLY_OUTLOOK_MCP_DISABLED_TOOLS",
  TOOL_NAME_PREFIX: "TOOL_NAME_PREFIX",
} as const;
